### PR TITLE
remove preventDefault on DropdownItem, so that link dropdown items still navigate

### PR DESCRIPTION
**Pull request by hwigmore**
@hamham91 @emma-floored

### CODE REVIEW

**Comment by hamham91** [comment]
👍

**Comment by hwigmore** [comment]
@MagdalenaHenke too! related convo in #eng-blocks channel!

**Comment by emma-floored** [comment]
👍

**Comment by hwigmore** [comment]
do i have publish rights or is that limited? would like to make a new release with this hotfix

**Comment by hamham91** [comment]
if you make an npm account I can add you, right now only Emma and I have publishing rights - thinking about making it a rundeck job so people don't need to be making accounts

**Comment by hwigmore** [comment]
ok! i'd say not important for now. you wanna just publish?

**Comment by MagdalenaHenke** [comment]
Wrote in eng-blocks - totally fine to take out again https://cbrebuild.slack.com/archives/C94LYR4EQ/p1556008602037800

**Pull request merged**
