### PR TITLE
dont remove margin-bottom on dropdown hover

### PR DESCRIPTION
**Pull request by hwigmore**
`blxUIText` (which we use in the dropdown) has a margin-bottom of 6px. it was getting set to 0px on hover.

@emma-floored

### CODE REVIEW

**Comment by hwigmore** [comment]
https://app.clubhouse.io/floored/stories/space/4029/blocks

**Comment by hwigmore** [comment]
@MagdalenaHenke another small one!

**Comment by hwigmore** [comment]
@helenCBRE

**Comment by helenCBRE** [comment]
👍 see it now! looks good to me

**Pull request merged**
