### PR TITLE
update colors (add secondary-03) and color page

### PR DESCRIPTION
**Pull request by emma-floored**
@hwigmore @MagdalenaHenke 
- add `secondary-03`, which was missing
- update styles on the "colors" page

### CODE REVIEW

**Comment by emma-floored** [comment]
https://app.clubhouse.io/blocks/story/34431/colors

**Comment by emma-floored** [comment]
https://app.clubhouse.io/blocks/story/34431/colors

**Comment by emma-floored** [comment]
[ch34431]

**Comment by emma-floored** [comment]
https://app.clubhouse.io/blocks/story/34431/colors

**Comment by emma-floored** [comment]
https://app.clubhouse.io/blocks/story/34431/colors

**Comment by emma-floored** [comment]
[ch34431]

**Comment by emma-floored** [comment]
https://app.clubhouse.io/blocks/story/34431/colors

**Comment by emma-floored** [comment]
https://app.clubhouse.io/blocks/story/34431/colors

**Comment by emma-floored** [comment]
https://app.clubhouse.io/blocks/story/34431/colors

**Comment by hwigmore** [comment]
the new old color column background makes it a little awkward with overflowing text

master
Screen Shot 2019-05-08 at 2 52 18 PM


branch
Screen Shot 2019-05-08 at 2 52 26 PM


but otherwise 👍 !!

**Comment by emma-floored** [comment]
Fair, although it looks like that in Zeplin, too, so I think I will leave it!

**Comment by hwigmore** [comment]
oh does it? ok then! 👍

**Pull request merged**
