### PR TITLE
Deploy with Netlify

### PR DESCRIPTION
**Pull request by emma-floored**
FYI @hwigmore @Jinsoo94 

(I'm gonna go ahead and merge this though)

This is a bunch of stuff to set up Netlify deploying for Blocks. Since we can run a command at deploy (`gulp build` in this case), we can now stop committing those gross generated files!

### CODE REVIEW

**Comment by emma-floored** [comment]
https://app.clubhouse.io/floored/story/10459/use-netlify-for-review-apps

**Comment by emma-floored** [comment]
[ch10459]

**Comment by emma-floored** [comment]
https://app.clubhouse.io/floored/story/10109/only-uglify-js-on-production-for-easier-debugging

**Comment by emma-floored** [comment]
[ch10109]

**Comment by hwigmore** [comment]
yay!! 

took a glance and saw that ruby version changed. do we need to install a later version / update the readme?

**Comment by emma-floored** [comment]
Oh good call. I forgot about that... I changed it b/c 2.4.3 is one of Netlify's supported versions, which is supposed to mean shorter deploy times. But, I also created these Gemfiles for Netlify which I ~think~ might change the setup instructions? So you might no longer have to manually install Jekyll, you could do a `bundle install` instead (https://bundler.io/). I'll investigate and update the README.

**Comment by hwigmore** [comment]
ah yeah i needed a `bundle install` (and `npm install`) to run it locally after this pr!

**Pull request merged**
