### PR TITLE
Close on click update

### PR DESCRIPTION
**Pull request by helenCBRE**
don't have a ticket - follow up fix to closeOnClick pr I recently made

### CODE REVIEW

**Comment by helenCBRE** [comment]
@emma-floored mind taking a quick look? i basically just wrapped my event in an undefined check bc sometimes that event is undefined

**Comment by emma-floored** [comment]
@helenCBRE what is the case where `e` is undefined?

**Comment by helenCBRE** [comment]
in a dropdown for example - when i select something in the dropdown rather than click somewhere outside of the dropdown to close

**Comment by helenCBRE** [comment]
oh hmm. how would we send an event when there isn't one happening from the interaction on the page?

**Comment by emma-floored** [comment]
sorry, led you astray! you can fix this by passing `e` here: https://github.com/floored/blocks/blob/master/packages/blocks-react/wrappers/keyControlledMenu.jsx#L41

and also just to be safe, here as well https://github.com/floored/blocks/blob/master/packages/blocks-react/wrappers/closeOnClick.jsx#L40

**Comment by helenCBRE** [comment]
@emma-floored mind taking a quick look?

**Comment by emma-floored** [comment]
uh oh something strange happened

**Comment by emma-floored** [comment]
with the update/merge

**Comment by emma-floored** [comment]
but your changes in commit de8eba0060ab8f6ff609033cf08f33dd6a7369ba look good

**Comment by helenCBRE** [comment]
woah i didn't even notice the massive file change until now rip. i rebased onto master before committing? i think i'll just close this pr and reopen it

**Pull request closed without merging**
