### PR TITLE
Remove blur() in TextField when pressing Enter

### PR DESCRIPTION
**Pull request by tariqporter**
@hwigmore @hamham91 

Very minor change to alter default behavior. 
`blur` prevents us focusing a particular element on `Enter` keypress, as `blur` essentially focuses `body`.

### CODE REVIEW

**Comment by emma-floored** [comment]
👍

**Comment by hwigmore** [comment]
minor, could simplify to match all the other event handlers now (`onKeyUp={props.onKeyUp}`) but either way 👍

**Comment by tariqporter** [comment]
@hwigmore Good catch

**Comment by hamham91** [comment]
👍

**Comment by hamham91** [comment]
Is there a case where we would want this behavior enabled via a flag?
```
<TextField
   ...
   blurOnEnter
/>
```

**Comment by tariqporter** [comment]
> Is there a case where we would want this behavior enabled via a flag?
> 
> ```
> <TextField
>    ...
>    blurOnEnter
> />
> ```

I think in the case that is wanted behaviour, the user should put `blur` in their own function

**Comment by hwigmore** [comment]
i'm open to a flag, but i also think that if a particular app wants that behavior, they can also just pass it as part of their `onKeyUp` or `onKeyDown` function.

**Comment by hwigmore** [comment]
👍 to merge! (or squash and merge, as we're starting to do for blocks)

can you also open up a new release called v0.1.3 and describe this change? in the same format as the other releases? 

thanks!!

**Comment by hwigmore** [comment]
gonna squash and merge this for you and add to the release notes...

**Comment by tariqporter** [comment]
Thanks!

**Pull request merged**
