### PR TITLE
add vertical ellipsis for popover

### PR DESCRIPTION
**Pull request by hwigmore**
@emma-floored @MagdalenaHenke 

screen shot 2018-09-24 at 7 28 07 pm

### CODE REVIEW

**Comment by hwigmore** [comment]
https://app.clubhouse.io/floored/story/10772/add-vertical-ellipsis-icon-for-popover

**Comment by hwigmore** [comment]
trying to figure out why ModalPreview and ButtonPreview changed as well...

**Comment by hwigmore** [comment]
oh looks like `ButtonPreview.js` and `ModalPreview.js` had changes that never got checked in (on master if i run `gulp server` i also see those files have been updated). i'll just leave those updates here

**Comment by hwigmore** [comment]
i added one more thing in here 🙊 

in our use case we need to `evt.preventDefault()` when we click our popover menu (it is within a larger button/link). i think/hope adding this on the blocks level will be ok for other popover use cases?

**Comment by emma-floored** [comment]
I think the `evt.preventDefault()` should be fine... looks good! 👍

**Pull request merged**
