### PR TITLE
update popover width so it doesnt get stuck at 124px

### PR DESCRIPTION
**Pull request by hwigmore**
i realized the popover min-width was making it so that popovers were _only_ 124px wide. this needed a `width: auto` to fix it. while i was in there, i peeked at the [popover spec](https://app.zeplin.io/project/5adf8fe14c3924b93d974cba/screen/5b6479a6ee18e58c1af71437) to grab the latest min/max

@emma-floored

### CODE REVIEW

**Comment by emma-floored** [comment]
oh sweet, I had made a ticket for this

**Comment by emma-floored** [comment]
https://app.clubhouse.io/floored/story/12930/tweak-popover-menu-width-styling

**Comment by emma-floored** [comment]
👍

**Comment by hwigmore** [comment]
oops, didn't even check clubhouse 😳

**Pull request merged**
