### PR TITLE
dont use content for table cell keys, to avoid react errors for duplicate keys

### PR DESCRIPTION
**Pull request by hwigmore**
really minor but we have a lot of the same data (or lack thereof) in our table cells and this change is to get rid of the duplicate key errors

### CODE REVIEW

**Comment by hamham91** [comment]
👍

**Comment by hamham91** [comment]
my only thought is maybe we want to have a per table key so we can support having multiple tables on the same page?

**Comment by hwigmore** [comment]
oh great idea. i can add that

**Comment by hwigmore** [comment]
@hamham91 added one more commit! great idea

**Comment by emma-floored** [comment]
👍

**Pull request merged**
