### PR TITLE
use rest operator in Icon

### PR DESCRIPTION
**Pull request by Jinsoo94**
[Clubhouse](https://app.clubhouse.io/blocks/story/38591/icon-spread-operator)

Hmm I am doing spread operator to reduce the number of lines, but its net increasing... :p

### CODE REVIEW

**Comment by Jinsoo94** [comment]
@emma-floored quick review?

**Comment by emma-floored** [comment]
lol I didn't even think about it increasing... how funny

**Comment by emma-floored** [comment]
lol I didn't even think about it increasing... how funny

Seems fine though! I can see if I can minimize the generated JavaScript some more.

👍

**Comment by MagdalenaHenke** [comment]
🌮 looks good!

**Pull request merged**
