### PR TITLE
make extra sure type styles are using the right font

### PR DESCRIPTION
**Pull request by emma-floored**
@MagdalenaHenke @Jinsoo94 Sooooooooo Heather 👀 made this ticket about LinkButton and Button text looking different, but some of us (me) weren't sure if that was real.

Before (compare the capital Gs - LinkButton on left, regular Button on right):
Screen Shot 2019-06-18 at 1 48 38 PM

I looked at the computed styles to see if there was some sort of letter spacing nonsense or something that was happening, and lo and behold...
LinkButton
Screen Shot 2019-06-18 at 12 25 11 PM
Buttons
Screen Shot 2019-06-18 at 12 25 04 PM

`system-ui`?????? Oh no. Buttons were for some reason not using Graphik. I guess it doesn't propagate down from `html` as much as I thought?? Anyway I sprinkled it everywhere in the typography styles so things should all be using the correct font now.

Now:
Screen Shot 2019-06-18 at 1 49 03 PM

### CODE REVIEW

**Comment by emma-floored** [comment]
https://app.clubhouse.io/blocks/story/34527/make-link-button-and-button-button-look-the-same

**Comment by Jinsoo94** [comment]
lol how did heather even notice this

**Comment by Jinsoo94** [comment]
looks good to me!

**Comment by emma-floored** [comment]
I have no idea how she saw it! @hwigmore your eyes did not deceive you

**Comment by hwigmore** [comment]
ahh yeah it was a system ui thing! it does seem mildly insane that i noticed it, but i swear there was a case where it looked obvious

**Comment by hwigmore** [comment]
to be fair, @probablydan also noticed this on site iq

**Comment by probablydan** [comment]
it's much more apparent when seeing our users use it on Windows Chrome - but yes, I caught it a while ago and I can't unsee. thanks for reporting/fixing!

**Pull request merged**
