### PR TITLE
have radio buttons use children vs props

### PR DESCRIPTION
**Pull request by emma-floored**
@MagdalenaHenke @Jinsoo94 pretty self explanatory

### CODE REVIEW

**Comment by emma-floored** [comment]
https://app.clubhouse.io/blocks/story/38733/have-radio-buttons-use-children-v-props

**Comment by Jinsoo94** [comment]
👍

**Comment by MagdalenaHenke** [comment]
Having a look at this now

**Comment by MagdalenaHenke** [comment]
Love it 🌮

**Pull request merged**
