### PR TITLE
classname insertion points for base modal

### PR DESCRIPTION
**Pull request by Jinsoo94**
Fixing merge conflicts of #190 
Did it so we can merge it quickly and do a deploy today!

### CODE REVIEW

**Comment by Jinsoo94** [comment]
@tariqporter @MagdalenaHenke

**Comment by graydonpleasants** [comment]
Works for us, seems like something in the build process has broken

**Comment by MagdalenaHenke** [comment]
@graydonpleasants - what do you mean with "something in the build process has broken"?

**Comment by MagdalenaHenke** [comment]
Looks good to me and locally building works, too. 🌮 here @Jinsoo94

**Comment by graydonpleasants** [comment]
sorry, just meant i was experiencing some weird local dev:docs behavior and was wondering if that what was failing the netlify checks

**Pull request merged**
