### PR TITLE
React preview

### PR DESCRIPTION
**Pull request by emma-floored**
@hwigmore @jforzano and maybe like @MagdalenaHenke ? More of an FYI/curious if this is useful to y'all (and also curious if you have any strong feelings about it).

I thought it would be useful (definitely for me, anyway) to be able to also view the Blocks React components on the documentation site so I can be sure I don't screw those up when I fiddle with styles and stuff.

This is not pretty so there are no links to this page from the root Blocks docs site - I just stuck all the React components on one page which can be accessed at `<base>/react-preview`.

screen shot 2018-07-05 at 4 55 47 pm

The React page itself is at docs/_javascript/preview.jsx - most of these changes are adding webpack, babel, etc to be able to transpile the JSX.

### CODE REVIEW

**Comment by jforzano** [comment]
This is great def useful!

**Comment by hwigmore** [comment]
so excited about this!! 👏 

but it doesn't seem to be working on the github page https://floored.github.io/blocks/react-preview/

**Comment by emma-floored** [comment]
UGH I bet I know why

**Comment by emma-floored** [comment]
@hwigmore should work now!

**Comment by hwigmore** [comment]
yayy beautiful!

**Pull request merged**
