### PR TITLE
Close on click update

### PR DESCRIPTION
**Pull request by helenCBRE**
https://app.clubhouse.io/floored/story/20805/make-elements-outside-of-open-element-unclickable-when-closing-open-element-with-closeonclick

### CODE REVIEW

**Comment by emma-floored** [comment]
https://app.clubhouse.io/floored/story/20805/make-elements-outside-of-open-element-unclickable-when-closing-open-element-with-closeonclick

**Comment by emma-floored** [comment]
(clubhouse integration only works if the ticket link is in a comment alone with nothing else -_-)

**Comment by emma-floored** [comment]
👍

**Comment by hwigmore** [comment]
👍

**Pull request merged**
