### PR TITLE
_Flex_ible base modal

### PR DESCRIPTION
**Pull request by hamham91**
Make the base modal flexy so we can have scrollable content that doesn't pop out of the modal.

Master:
Screen Shot 2019-05-16 at 2 16 02 AM

This branch:
Screen Shot 2019-05-16 at 2 16 34 AM

I tested a couple other modals and didn't see any issues.

### CODE REVIEW

**Comment by hwigmore** [comment]
ooh love this. will test in a bit

**Comment by hwigmore** [comment]
👍

**Comment by hamham91** [comment]
Tariq was the one who solved this issue, but he was overriding the styling on the first child div under blx-modal and I wanted to push the change upstream!

**Comment by emma-floored** [comment]
👍

**Pull request merged**
