### PR TITLE
add .gitattributes file

### PR DESCRIPTION
**Pull request by MagdalenaHenke**
Hey folks,

I think we probably all love a world where the files automatically created into `/dist/` don't show on PR requests. Adding them to `.gitattributes` makes it so that those files show as minified on pull requests by default.

https://help.github.com/en/articles/customizing-how-changed-files-appear-on-github

For testing: add the `.gitattributes` file to your project, change something else, regenerate dist, push that branch, look at the diff. 
Or look [here for an example of a diff **with** ignoring enabled](https://github.com/floored/blocks/compare/lena/ignoreMe) and here the same diff [without the .gitattributes file](https://github.com/floored/blocks/compare/lena/ignoreMeToo).

### CODE REVIEW

**Comment by MagdalenaHenke** [comment]
@Jinsoo94 @emma-floored - would you have a look?

**Comment by emma-floored** [comment]
👍 💐 I didn't know this was a thing, this is great!

**Comment by Jinsoo94** [comment]
great! 🌮

**Comment by sageknives** [comment]
Yes please.

**Comment by MagdalenaHenke** [comment]
This got merged a while ago!

**Pull request merged**
