### PR TITLE
disable focus if tab is disabled

### PR DESCRIPTION
**Pull request by Jinsoo94**
[Clubhouse](https://app.clubhouse.io/blocks/story/38657/able-to-tab-focus-disabled-tabs)

Setting tabIndex to -1 makes element inaccessible via tab key. This change was easy to implement with the rest operator update! (Since I only have to update the parent)

### CODE REVIEW

**Comment by Jinsoo94** [comment]
@emma-floored @MagdalenaHenke ready for review!

**Comment by Jinsoo94** [comment]
https://app.clubhouse.io/blocks/story/38657/able-to-tab-focus-disabled-tabs

**Comment by emma-floored** [comment]
this works great for the disabled one, but maybe it's not doing quite the right thing for link tabs? if you tab through the left sidebar navigation, it's doing a weird double focus thing that it doesn't do on master

Screen Shot 2019-06-19 at 2 18 13 PM

**Comment by Jinsoo94** [comment]
@emma-floored fixed it!

**Comment by emma-floored** [comment]
👍

**Pull request merged**
