### PR TITLE
Dropdown updates

### PR DESCRIPTION
**Pull request by hamham91**
Vertically center text in dropdowns.
Enable custom link elements in dropdowns (to match buttons).

Master:
Screen Shot 2019-03-28 at 4 48 29 PM

This PR:
Screen Shot 2019-03-28 at 4 48 18 PM

### CODE REVIEW

**Comment by emma-floored** [comment]
Fine with this but wondering why I don't see it on master?

Screen Shot 2019-03-28 at 5 06 04 PM

**Comment by hamham91** [comment]
Looks like a Firefox issue :upside_down_face:

**Comment by emma-floored** [comment]
👍

**Comment by hwigmore** [comment]
ooh can i add two small commits to this PR?? or can do it separately?

**Comment by emma-floored** [comment]
dooo itttttt (if that's ok with you @hamham91 !!)

**Comment by hamham91** [comment]
oh yes please

**Comment by hwigmore** [comment]
https://app.clubhouse.io/floored/story/29480/dropdown-styles

**Comment by hwigmore** [comment]
@hamham91 @emma-floored would you mind taking a quick look to make sure my last two commits didnt unintentionally mess other things up.

**Comment by hwigmore** [comment]
for the filled vs default color, we had the code there but there was a specificity war and the default color was winning so i just moved the styles

**Comment by hamham91** [comment]
👍

**Comment by emma-floored** [comment]
👍

**Pull request merged**
