### PR TITLE
Remove * selector to replace with class

### PR DESCRIPTION
**Pull request by tariqporter**
* is bad, should use .blx-button instead
@emma-floored @hwigmore

### CODE REVIEW

**Comment by tariqporter** [comment]
https://app.clubhouse.io/floored/story/11161/make-button-group-selector-more-specific

**Comment by emma-floored** [comment]
Sweet! Can you run `gulp server` on this branch and commit the generated files that produces? Should be `blocks.css` and `docs/css/blocks.css`.

**Comment by tariqporter** [comment]
Done. Let me know if this is ok

**Comment by emma-floored** [comment]
looks good! 👍 feel free to merge

**Pull request merged**
