### PR TITLE
popover vertical alignment and subtitle doc updates

### PR DESCRIPTION
**Pull request by hwigmore**
[Clubhouse](https://app.clubhouse.io/floored/story/12801/fix-popover-text-icon-vertical-alignment)

the first commit isn't directly related to the bug, but i think it's helpful to see that that class does come with a built-in margin

### CODE REVIEW

**Comment by Jinsoo94** [comment]
Looks great! 

One thing, this is super nitpicky + my eye could just be weird, so I want more people's input, but I think blx-icon is not at the vertical center of blx-popover-trigger. Adding `display: flex` to .blx-popover-trigger vertically aligns it.

**Comment by hwigmore** [comment]
ooh good eye! will update

**Comment by Jinsoo94** [comment]
👍

**Comment by emma-floored** [comment]
👍

**Pull request merged**
